New Topics added for Cloud Network and Network Event Broker tools
vmware/photon pull request #1218
Opened 2021-07-26 11:29 UTC by dsoumay

Hi,
I have added two new topics (2 new pages), and images under the Managing Network Configuration topic in the Administration guide. Please review the changes and approve them if they look good.

Thanks,
Soumay

2021-07-26 16:13 UTC, ssahani requested changes

2021-07-26 16:13 UTC, ssahani commented on content/en/docs/administration-guide/managing-network-configuration/using-network-event-broker.md
> +	❯ systemctl status network-broker.service
please drop it

2021-07-26 16:13 UTC, ssahani commented on content/en/docs/administration-guide/managing-network-configuration/using-network-event-broker.md
> +
till here. These are not required for documentation

2021-07-26 17:56 UTC, mikeroySoft commented
layout wise it looks okay... we can merge once we have the changes that @ssahani proposed.

2021-07-27 09:41 UTC, ssahani commented on content/en/docs/administration-guide/managing-network-configuration/configuring-a-secondary-network-interface-using-cloud-network.md
> +
It detects the available instances using netlink. -> It detects the available interfaces using netlink.

2021-07-27 14:10 UTC, ssahani commented
LGTM .  Probably squash the last 2 commits  @mikeroySoft  ?

2021-07-27 15:13 UTC, merged